// This file is generated by Sapper — do not edit it!
import root from "../routes/_layout.html";
import error from "../routes/_error.html";

const d = decodeURIComponent;

const index = {
	js: () => import("../routes/index.html"),
	css: "__SAPPER_CSS_PLACEHOLDER:index.html__"
};
const guide = {
	js: () => import("../routes/guide/index.html"),
	css: "__SAPPER_CSS_PLACEHOLDER:guide/index.html__"
};

export const manifest = {
	ignore: [/^\/guide.json$/],

	pages: [
		{
			// index.html
			pattern: /^\/?$/,
			parts: [
				{ component: index }
			]
		},

		{
			// guide/index.html
			pattern: /^\/guide\/?$/,
			parts: [
				null,
				{ component: guide }
			]
		}
	],

	root,

	error
};

// this is included for legacy reasons
export const routes = {};

import("/Users/208311/Development/SVELTE/sapper.svelte.technology/node_modules/sapper/sapper-dev-client.js").then(client => {
	client.connect(10000);
});