// This file is generated by Sapper — do not edit it!
import * as route_guide_json from "../routes/guide/index.json.js";
import index from "../routes/index.html";
import guide from "../routes/guide/index.html";
import root from "../routes/_layout.html";
import error from "../routes/_error.html";

const d = decodeURIComponent;

export const manifest = {
	server_routes: [
		{
			// guide/index.json.js
			pattern: /^\/guide.json$/,
			handlers: route_guide_json,
			params: () => ({})
		}
	],

	pages: [
		{
			// index.html
			pattern: /^\/?$/,
			parts: [
				{ name: "index", file: "index.html", component: index }
			]
		},

		{
			// guide/index.html
			pattern: /^\/guide\/?$/,
			parts: [
				null,
				{ name: "guide", file: "guide/index.html", component: guide }
			]
		}
	],

	root,

	error
};

// this is included for legacy reasons
export const routes = {};