// This file is generated by Sapper — do not edit it!
export const timestamp = 1537755891555;

export const files = [
	"favicon.ico",
	"favicon.png",
	"fonts/Inconsolata/Inconsolata-Bold.woff",
	"fonts/Inconsolata/Inconsolata-Bold.woff2",
	"fonts/Inconsolata/Inconsolata-Regular.woff",
	"fonts/Inconsolata/Inconsolata-Regular.woff2",
	"fonts/Inconsolata/OFL.txt",
	"fonts/Rajdhani/Rajdhani-Bold.woff",
	"fonts/Rajdhani/Rajdhani-Bold.woff2",
	"fonts/Rajdhani/Rajdhani-Medium.woff",
	"fonts/Rajdhani/Rajdhani-Medium.woff2",
	"fonts/Rajdhani/Rajdhani-Regular.woff",
	"fonts/Rajdhani/Rajdhani-Regular.woff2",
	"fonts/Roboto/Roboto-Bold.woff",
	"fonts/Roboto/Roboto-Bold.woff2",
	"fonts/Roboto/Roboto-Light.woff",
	"fonts/Roboto/Roboto-Light.woff2",
	"fonts/Roboto/Roboto-LightItalic.woff",
	"fonts/Roboto/Roboto-LightItalic.woff2",
	"global.css",
	"images/twitter-card.png",
	"manifest.json",
	"package.json",
	"sapper-logo-192.png",
	"sapper-logo-512.png"
];
export { files as assets }; // legacy

export const shell = [
	"client/client.2592ce3d.js",
	"client/chunk.3df7add4.js",
	"client/chunk.3ebc741a.js",
	"client/index.a970adf6.js",
	"client/index.d8894e09.js",
	"client/sapper-dev-client.c1ed07a9.js",
	"client/Toast.5da78cbd.js"
];

export const routes = [
	{ pattern: /^\/?$/ },
	{ pattern: /^\/guide\/?$/ }
];