// This file is generated by Sapper — do not edit it!
export const routes = [
	{ pattern: /^\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "_" */ '../../routes/index.html') },
	{ error: '4xx', load: () => import(/* webpackChunkName: "_4xx" */ '../../routes/4xx.html') },
	{ error: '5xx', load: () => import(/* webpackChunkName: "_5xx" */ '../../routes/5xx.html') },
	{ pattern: /^\/guide\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "guide" */ '../../routes/guide/index.html') }
];