// This file is generated by Sapper — do not edit it!
export const timestamp = 1518973061624;

export const assets = [
	"favicon.ico",
	"favicon.png",
	"fonts/Inconsolata/Inconsolata-Bold.woff",
	"fonts/Inconsolata/Inconsolata-Bold.woff2",
	"fonts/Inconsolata/Inconsolata-Regular.woff",
	"fonts/Inconsolata/Inconsolata-Regular.woff2",
	"fonts/Inconsolata/OFL.txt",
	"fonts/Rajdhani/Rajdhani-Bold.woff",
	"fonts/Rajdhani/Rajdhani-Bold.woff2",
	"fonts/Rajdhani/Rajdhani-Medium.woff",
	"fonts/Rajdhani/Rajdhani-Medium.woff2",
	"fonts/Rajdhani/Rajdhani-Regular.woff",
	"fonts/Rajdhani/Rajdhani-Regular.woff2",
	"fonts/Roboto/Roboto-Bold.woff",
	"fonts/Roboto/Roboto-Bold.woff2",
	"fonts/Roboto/Roboto-Light.woff",
	"fonts/Roboto/Roboto-Light.woff2",
	"fonts/Roboto/Roboto-LightItalic.woff",
	"fonts/Roboto/Roboto-LightItalic.woff2",
	"global.css",
	"images/twitter-card.png",
	"manifest.json",
	"sapper-logo-192.png",
	"sapper-logo-512.png"
];

export const shell = [
	"/client/_.0.42dec0d2b3bd56f4f941.js",
	"/client/guide.1.42dec0d2b3bd56f4f941.js",
	"/client/_5xx.2.42dec0d2b3bd56f4f941.js",
	"/client/_4xx.3.42dec0d2b3bd56f4f941.js",
	"/client/4.4.42dec0d2b3bd56f4f941.js",
	"/client/5.5.42dec0d2b3bd56f4f941.js",
	"/client/main.42dec0d2b3bd56f4f941.js"
];

export const routes = [
	{ pattern: /^\/?$/ },
	{ pattern: /^\/guide\/?$/ }
];