// This file is generated by Sapper — do not edit it!
import _ from '../../routes/index.html';
import _4xx from '../../routes/4xx.html';
import _5xx from '../../routes/5xx.html';
import guide from '../../routes/guide/index.html';
import * as api_guide_contents from '../../routes/api/guide-contents.js';
import * as api_guide from '../../routes/api/guide.js';

export const routes = [
	{ id: '_', type: 'page', pattern: /^\/?$/, params: () => ({}), module: _ },
	{ error: '4xx', module: _4xx },
	{ error: '5xx', module: _5xx },
	{ id: 'guide', type: 'page', pattern: /^\/guide\/?$/, params: () => ({}), module: guide },
	{ id: 'api_guide_contents', type: 'route', pattern: /^\/api\/guide-contents\/?$/, params: () => ({}), module: api_guide_contents },
	{ id: 'api_guide', type: 'route', pattern: /^\/api\/guide\/?$/, params: () => ({}), module: api_guide }
];